version: "3.4"
services:
  frontend:
     image: frontend
     build:
       context: ./frontend
       dockerfile: Dockerfile
     container_name: front-end 
     restart: always
     expose:
       - 3000
     ports:
       - "3000:80"
     tty: true
     networks:
      - employee
  backend:
     image: backend
     build:
       context: ./backend
       dockerfile: Dockerfile
     container_name: back-end 
     restart: always
     depends_on:
       - mysql-db
     expose:
       - 9001
     ports:
       - "9001:9001"
     tty: true
     networks:
      - employee
  mysql-db:
    image: mysql-db
    container_name: mysql-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - emp-db:/var/lib/mysql
    networks:
      - employee
volumes:
    emp-db:
      external: true
        
networks:
    employee:
      driver: "bridge"
      external: true
        