replicaCount: 2
image:
  repository: nexus.zymrinc.com:8083/devops-proj-4/frontend:${RELEASE_TAG}
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: 
  - name: nexus-creds
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  
service:
  type: NodePort
  port: 9001
  targetport: 9001
  nodeport: 32345

ingress:
  enabled: false
  
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
env:
   - name: MYSQL_DATABASE
     valueFrom:        
       configMapKeyRef:
         name: config-envs
         key: MYSQL_DATABASE
   - name: CORS_ALLOW_URL
     valueFrom:        
       configMapKeyRef:
         name: config-envs
         key: CORS_ALLOW_URL
   - name: MYSQL_ROOT_USER
     valueFrom:        
       configMapKeyRef:
         name: config-envs
         key: MYSQL_ROOT_USER
   - name: MYSQL_CONNECTION
     valueFrom:        
       configMapKeyRef:
         name: config-envs
         key: MYSQL_CONNECTION
   
   - name: MYSQL_ROOT_PASSWORD
     valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: password
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
