apiVersion: apps/v1
kind: Deployment     
metadata:
  name: backend
  labels:            
    app: backend
spec:
  replicas: 1         
  selector:
    matchLabels:
      app: backend
  template:     
    metadata:
      labels:          
        app: backend
    spec:     
      containers:
      - name: backend
        image:  nexus.zymrinc.com:8083/devops-proj-4/backend:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 9001
        env:             
        - name:  MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: CORS_ALLOW_URL
          value: ${K8S_CORS_ALLOW_URL}
        - name: MYSQL_ROOT_USER
          value: ${MYSQL_ROOT_USER}
        - name: MYSQL_CONNECTION
          value: ${MYSQL_CONNECTION}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      restartPolicy: Always
      imagePullSecrets:
        - name: nexus-creds
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:              
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    port: 9001
    targetPort: 9001
    nodePort: 32345