apiVersion: apps/v1
kind: Deployment     
metadata:
  name: backend
  labels:            
    app: backend
spec:
  replicas: 1         
  selector:
    matchLabels:
      app: backend
  template:     
    metadata:
      labels:          
        app: backend
    spec:     
      containers:
      - name: backend
        image:  nexus.zymrinc.com:8083/devops-proj-4/backend:${RELEASE_TAG}
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 9001
        env:
          - name:
            valueFrom:        
              configMapKeyRef:
                name: config-envs
                key: MYSQL_DATABASE
          - name:
            valueFrom:        
              configMapKeyRef:
                name: config-envs
                key: CORS_ALLOW_URL
          - name:
            valueFrom:        
              configMapKeyRef:
                name: config-envs
                key: MYSQL_ROOT_USER
          - name:
            valueFrom:        
              configMapKeyRef:
                name: config-envs
                key: MYSQL_CONNECTION
          
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: password
      restartPolicy: Always
      imagePullSecrets:
        - name: nexus-creds
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:              
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    port: 9001
    targetPort: 9001
    nodePort: 32345