apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      appdb: mysql-db
  replicas: 1
  serviceName: mysql-db
  template:
    metadata:
      labels:
        appdb: mysql-db
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: nexus-creds
      containers:
      - name: mysql-db
        image:  nexus.zymrinc.com:8083/devops-proj-4/mysql-db:${RELEASE_TAG}
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: MYSQL_DATABASE
            valueFrom:        
               configMapKeyRef:
                 name: config-envs
                 key: MYSQL_DATABASE
          - name: MYSQL_ROOT_USER
            valueFrom:        
              configMapKeyRef:
                name: config-envs
                key: MYSQL_ROOT_USER 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mysql-secret 
                key: password
        ports:
        - containerPort: 3306
        volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: proj4-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    appdb: mysql-db