kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nexus.zymrinc.com:8083/devops-proj-4/frontend:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: nexus-creds

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31234
  selector:
    app: frontend