kind: Deployment
apiVersion: apps/v1
metadata:
  name: 
  {{- include "frontend.name" . | nindent 4 }}
  labels: 
  {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.image.repository | quote }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
      restartPolicy: Always
      imagePullSecrets:
        - name: nexus-creds