
replicaCount: 1
image:
  repository: nexus.zymrinc.com:8083/devops-proj-4/frontend:${RELEASE_TAG}
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort
  port: 80
  nodePort: 31234
  name: frontend
containers:
  name: frontend

